//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.13 at 09:03:47 PM EDT 
//


package gov.sc.sg.engineering.hydro;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CensorCodeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CensorCodeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="lt"/>
 *     &lt;enumeration value="gt"/>
 *     &lt;enumeration value="nc"/>
 *     &lt;enumeration value="nd"/>
 *     &lt;enumeration value="pnq"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CensorCodeEnum")
@XmlEnum
public enum CensorCodeEnum {

    @XmlEnumValue("lt")
    LT("lt"),
    @XmlEnumValue("gt")
    GT("gt"),
    @XmlEnumValue("nc")
    NC("nc"),
    @XmlEnumValue("nd")
    ND("nd"),
    @XmlEnumValue("pnq")
    PNQ("pnq");
    private final String value;

    CensorCodeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CensorCodeEnum fromValue(String v) {
        for (CensorCodeEnum c: CensorCodeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
