//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.13 at 09:03:47 PM EDT 
//


package gov.sc.sg.engineering.hydro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CensorCodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CensorCodeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="censorCode" type="{http://www.cuahsi.org/waterML/1.1/}CensorCodeCodeList"/>
 *         &lt;element name="censorCodeDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="censorCodeID" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CensorCodeType", propOrder = {
    "censorCode",
    "censorCodeDescription"
})
public class CensorCodeType {

    @XmlElement(required = true)
    protected String censorCode;
    @XmlElement(required = true)
    protected String censorCodeDescription;
    @XmlAttribute(name = "censorCodeID")
    protected Integer censorCodeID;

    /**
     * Gets the value of the censorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCensorCode() {
        return censorCode;
    }

    /**
     * Sets the value of the censorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCensorCode(String value) {
        this.censorCode = value;
    }

    /**
     * Gets the value of the censorCodeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCensorCodeDescription() {
        return censorCodeDescription;
    }

    /**
     * Sets the value of the censorCodeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCensorCodeDescription(String value) {
        this.censorCodeDescription = value;
    }

    /**
     * Gets the value of the censorCodeID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCensorCodeID() {
        return censorCodeID;
    }

    /**
     * Sets the value of the censorCodeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCensorCodeID(Integer value) {
        this.censorCodeID = value;
    }

}
