//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.13 at 09:03:47 PM EDT 
//


package gov.sc.sg.engineering.hydro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for LabMethodType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LabMethodType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="labCode" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="labName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="labOrganization" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="labMethodName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="labMethodDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="labMethodLink" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="labSourceDetails" type="{http://www.cuahsi.org/waterML/1.1/}SourceType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="labMethodID" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LabMethodType", propOrder = {
    "labCode",
    "labName",
    "labOrganization",
    "labMethodName",
    "labMethodDescription",
    "labMethodLink",
    "labSourceDetails"
})
public class LabMethodType {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String labCode;
    protected String labName;
    protected String labOrganization;
    protected String labMethodName;
    protected String labMethodDescription;
    protected String labMethodLink;
    protected SourceType labSourceDetails;
    @XmlAttribute(name = "labMethodID")
    protected Integer labMethodID;

    /**
     * Gets the value of the labCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabCode() {
        return labCode;
    }

    /**
     * Sets the value of the labCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabCode(String value) {
        this.labCode = value;
    }

    /**
     * Gets the value of the labName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabName() {
        return labName;
    }

    /**
     * Sets the value of the labName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabName(String value) {
        this.labName = value;
    }

    /**
     * Gets the value of the labOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabOrganization() {
        return labOrganization;
    }

    /**
     * Sets the value of the labOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabOrganization(String value) {
        this.labOrganization = value;
    }

    /**
     * Gets the value of the labMethodName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabMethodName() {
        return labMethodName;
    }

    /**
     * Sets the value of the labMethodName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabMethodName(String value) {
        this.labMethodName = value;
    }

    /**
     * Gets the value of the labMethodDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabMethodDescription() {
        return labMethodDescription;
    }

    /**
     * Sets the value of the labMethodDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabMethodDescription(String value) {
        this.labMethodDescription = value;
    }

    /**
     * Gets the value of the labMethodLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabMethodLink() {
        return labMethodLink;
    }

    /**
     * Sets the value of the labMethodLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabMethodLink(String value) {
        this.labMethodLink = value;
    }

    /**
     * Gets the value of the labSourceDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SourceType }
     *     
     */
    public SourceType getLabSourceDetails() {
        return labSourceDetails;
    }

    /**
     * Sets the value of the labSourceDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceType }
     *     
     */
    public void setLabSourceDetails(SourceType value) {
        this.labSourceDetails = value;
    }

    /**
     * Gets the value of the labMethodID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLabMethodID() {
        return labMethodID;
    }

    /**
     * Sets the value of the labMethodID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLabMethodID(Integer value) {
        this.labMethodID = value;
    }

}
