//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.13 at 09:03:47 PM EDT 
//


package gov.sc.sg.engineering.hydro;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for latLonLineString complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="latLonLineString">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.cuahsi.org/waterML/1.1/}GeogLocationType">
 *       &lt;sequence>
 *         &lt;element name="coordLatLong" type="{http://www.cuahsi.org/waterML/1.1/}CoordType" maxOccurs="unbounded" minOccurs="2"/>
 *       &lt;/sequence>
 *       &lt;attribute name="zDirection">
 *         &lt;simpleType>
 *           &lt;union memberTypes=" {http://www.w3.org/2001/XMLSchema}string {http://www.cuahsi.org/waterML/1.1/}zDirectionEnum">
 *           &lt;/union>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "latLonLineString", propOrder = {
    "coordLatLong"
})
public class LatLonLineString
    extends GeogLocationType
{

    @XmlElement(required = true)
    protected List<CoordType> coordLatLong;
    @XmlAttribute(name = "zDirection")
    protected String zDirection;

    /**
     * Gets the value of the coordLatLong property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coordLatLong property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoordLatLong().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoordType }
     * 
     * 
     */
    public List<CoordType> getCoordLatLong() {
        if (coordLatLong == null) {
            coordLatLong = new ArrayList<CoordType>();
        }
        return this.coordLatLong;
    }

    /**
     * Gets the value of the zDirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZDirection() {
        return zDirection;
    }

    /**
     * Sets the value of the zDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZDirection(String value) {
        this.zDirection = value;
    }

}
