//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.13 at 09:03:47 PM EDT 
//


package gov.sc.sg.engineering.hydro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for OffsetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OffsetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="offsetTypeCode" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="offsetValue" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="offsetDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="unit" type="{http://www.cuahsi.org/waterML/1.1/}UnitsType"/>
 *         &lt;element name="offsetIsVertical" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="offsetAzimuthDegrees" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="offsetTypeID" type="{http://www.cuahsi.org/waterML/1.1/}positiveInt" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OffsetType", propOrder = {
    "offsetTypeCode",
    "offsetValue",
    "offsetDescription",
    "unit",
    "offsetIsVertical",
    "offsetAzimuthDegrees"
})
public class OffsetType {

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String offsetTypeCode;
    protected Float offsetValue;
    protected String offsetDescription;
    @XmlElement(required = true)
    protected UnitsType unit;
    @XmlElement(defaultValue = "true")
    protected boolean offsetIsVertical;
    protected Integer offsetAzimuthDegrees;
    @XmlAttribute(name = "offsetTypeID")
    protected Integer offsetTypeID;

    /**
     * Gets the value of the offsetTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffsetTypeCode() {
        return offsetTypeCode;
    }

    /**
     * Sets the value of the offsetTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffsetTypeCode(String value) {
        this.offsetTypeCode = value;
    }

    /**
     * Gets the value of the offsetValue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getOffsetValue() {
        return offsetValue;
    }

    /**
     * Sets the value of the offsetValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setOffsetValue(Float value) {
        this.offsetValue = value;
    }

    /**
     * Gets the value of the offsetDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffsetDescription() {
        return offsetDescription;
    }

    /**
     * Sets the value of the offsetDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffsetDescription(String value) {
        this.offsetDescription = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link UnitsType }
     *     
     */
    public UnitsType getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitsType }
     *     
     */
    public void setUnit(UnitsType value) {
        this.unit = value;
    }

    /**
     * Gets the value of the offsetIsVertical property.
     * 
     */
    public boolean isOffsetIsVertical() {
        return offsetIsVertical;
    }

    /**
     * Sets the value of the offsetIsVertical property.
     * 
     */
    public void setOffsetIsVertical(boolean value) {
        this.offsetIsVertical = value;
    }

    /**
     * Gets the value of the offsetAzimuthDegrees property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOffsetAzimuthDegrees() {
        return offsetAzimuthDegrees;
    }

    /**
     * Sets the value of the offsetAzimuthDegrees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOffsetAzimuthDegrees(Integer value) {
        this.offsetAzimuthDegrees = value;
    }

    /**
     * Gets the value of the offsetTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOffsetTypeID() {
        return offsetTypeID;
    }

    /**
     * Sets the value of the offsetTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOffsetTypeID(Integer value) {
        this.offsetTypeID = value;
    }

}
