//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.13 at 09:03:47 PM EDT 
//


package gov.sc.sg.engineering.hydro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SampleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SampleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="labSampleCode" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="sampleType" type="{http://www.cuahsi.org/waterML/1.1/}SampleTypeCodeList" minOccurs="0"/>
 *         &lt;element name="labMethod" type="{http://www.cuahsi.org/waterML/1.1/}LabMethodType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="sampleID" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SampleType", propOrder = {
    "labSampleCode",
    "sampleType",
    "labMethod"
})
public class SampleType {

    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String labSampleCode;
    protected String sampleType;
    protected LabMethodType labMethod;
    @XmlAttribute(name = "sampleID")
    protected Integer sampleID;

    /**
     * Gets the value of the labSampleCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabSampleCode() {
        return labSampleCode;
    }

    /**
     * Sets the value of the labSampleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabSampleCode(String value) {
        this.labSampleCode = value;
    }

    /**
     * Gets the value of the sampleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampleType() {
        return sampleType;
    }

    /**
     * Sets the value of the sampleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampleType(String value) {
        this.sampleType = value;
    }

    /**
     * Gets the value of the labMethod property.
     * 
     * @return
     *     possible object is
     *     {@link LabMethodType }
     *     
     */
    public LabMethodType getLabMethod() {
        return labMethod;
    }

    /**
     * Sets the value of the labMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabMethodType }
     *     
     */
    public void setLabMethod(LabMethodType value) {
        this.labMethod = value;
    }

    /**
     * Gets the value of the sampleID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSampleID() {
        return sampleID;
    }

    /**
     * Sets the value of the sampleID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSampleID(Integer value) {
        this.sampleID = value;
    }

}
