//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.13 at 09:03:47 PM EDT 
//


package gov.sc.sg.engineering.hydro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for TimeZoneType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimeZoneType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="zoneOffset" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *       &lt;attribute name="zoneAbbreviation" type="{http://www.w3.org/2001/XMLSchema}token" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimeZoneType")
@XmlSeeAlso({
    gov.sc.sg.engineering.hydro.SiteInfoType.TimeZoneInfo.DefaultTimeZone.class,
    gov.sc.sg.engineering.hydro.SiteInfoType.TimeZoneInfo.DaylightSavingsTimeZone.class,
    gov.sc.sg.engineering.hydro.DataSetInfoType.TimeZoneInfo.DefaultTimeZone.class,
    gov.sc.sg.engineering.hydro.DataSetInfoType.TimeZoneInfo.DaylightSavingsTimeZone.class
})
public class TimeZoneType {

    @XmlAttribute(name = "zoneOffset", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String zoneOffset;
    @XmlAttribute(name = "zoneAbbreviation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String zoneAbbreviation;

    /**
     * Gets the value of the zoneOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZoneOffset() {
        return zoneOffset;
    }

    /**
     * Sets the value of the zoneOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZoneOffset(String value) {
        this.zoneOffset = value;
    }

    /**
     * Gets the value of the zoneAbbreviation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZoneAbbreviation() {
        return zoneAbbreviation;
    }

    /**
     * Sets the value of the zoneAbbreviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZoneAbbreviation(String value) {
        this.zoneAbbreviation = value;
    }

}
