//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.13 at 09:03:47 PM EDT 
//


package gov.sc.sg.engineering.hydro;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TsValuesSingleVariableType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TsValuesSingleVariableType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="value" type="{http://www.cuahsi.org/waterML/1.1/}ValueSingleVariable" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="units" type="{http://www.cuahsi.org/waterML/1.1/}UnitsType" minOccurs="0"/>
 *         &lt;element name="qualifier" type="{http://www.cuahsi.org/waterML/1.1/}QualifierType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="qualityControlLevel" type="{http://www.cuahsi.org/waterML/1.1/}QualityControlLevelType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="method" type="{http://www.cuahsi.org/waterML/1.1/}MethodType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="source" type="{http://www.cuahsi.org/waterML/1.1/}SourceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="offset" type="{http://www.cuahsi.org/waterML/1.1/}OffsetType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="sample" type="{http://www.cuahsi.org/waterML/1.1/}SampleType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="censorCode" type="{http://www.cuahsi.org/waterML/1.1/}CensorCodeType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TsValuesSingleVariableType", propOrder = {
    "value",
    "units",
    "qualifier",
    "qualityControlLevel",
    "method",
    "source",
    "offset",
    "sample",
    "censorCode"
})
public class TsValuesSingleVariableType {

    protected List<ValueSingleVariable> value;
    protected UnitsType units;
    protected List<QualifierType> qualifier;
    protected List<QualityControlLevelType> qualityControlLevel;
    protected List<MethodType> method;
    protected List<SourceType> source;
    protected List<OffsetType> offset;
    protected List<SampleType> sample;
    protected List<CensorCodeType> censorCode;

    /**
     * Gets the value of the value property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the value property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueSingleVariable }
     * 
     * 
     */
    public List<ValueSingleVariable> getValue() {
        if (value == null) {
            value = new ArrayList<ValueSingleVariable>();
        }
        return this.value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link UnitsType }
     *     
     */
    public UnitsType getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitsType }
     *     
     */
    public void setUnits(UnitsType value) {
        this.units = value;
    }

    /**
     * Gets the value of the qualifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QualifierType }
     * 
     * 
     */
    public List<QualifierType> getQualifier() {
        if (qualifier == null) {
            qualifier = new ArrayList<QualifierType>();
        }
        return this.qualifier;
    }

    /**
     * Gets the value of the qualityControlLevel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualityControlLevel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualityControlLevel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QualityControlLevelType }
     * 
     * 
     */
    public List<QualityControlLevelType> getQualityControlLevel() {
        if (qualityControlLevel == null) {
            qualityControlLevel = new ArrayList<QualityControlLevelType>();
        }
        return this.qualityControlLevel;
    }

    /**
     * Gets the value of the method property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the method property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMethod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MethodType }
     * 
     * 
     */
    public List<MethodType> getMethod() {
        if (method == null) {
            method = new ArrayList<MethodType>();
        }
        return this.method;
    }

    /**
     * Gets the value of the source property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the source property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SourceType }
     * 
     * 
     */
    public List<SourceType> getSource() {
        if (source == null) {
            source = new ArrayList<SourceType>();
        }
        return this.source;
    }

    /**
     * Gets the value of the offset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOffset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OffsetType }
     * 
     * 
     */
    public List<OffsetType> getOffset() {
        if (offset == null) {
            offset = new ArrayList<OffsetType>();
        }
        return this.offset;
    }

    /**
     * Gets the value of the sample property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sample property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSample().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SampleType }
     * 
     * 
     */
    public List<SampleType> getSample() {
        if (sample == null) {
            sample = new ArrayList<SampleType>();
        }
        return this.sample;
    }

    /**
     * Gets the value of the censorCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the censorCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCensorCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CensorCodeType }
     * 
     * 
     */
    public List<CensorCodeType> getCensorCode() {
        if (censorCode == null) {
            censorCode = new ArrayList<CensorCodeType>();
        }
        return this.censorCode;
    }

}
