//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.13 at 09:03:47 PM EDT 
//


package gov.sc.sg.engineering.hydro;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for zDirectionEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="zDirectionEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PositiveUp"/>
 *     &lt;enumeration value="PositiveDown"/>
 *     &lt;enumeration value="Depth"/>
 *     &lt;enumeration value="Altitude"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "zDirectionEnum")
@XmlEnum
public enum ZDirectionEnum {

    @XmlEnumValue("PositiveUp")
    POSITIVE_UP("PositiveUp"),
    @XmlEnumValue("PositiveDown")
    POSITIVE_DOWN("PositiveDown"),
    @XmlEnumValue("Depth")
    DEPTH("Depth"),
    @XmlEnumValue("Altitude")
    ALTITUDE("Altitude");
    private final String value;

    ZDirectionEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ZDirectionEnum fromValue(String v) {
        for (ZDirectionEnum c: ZDirectionEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
